version: '3'
services:

# Devops
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - ./.env
    restart: always
    # ports:
    #   - "8080:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-network

  # Nginx
  nginx:
    image: nginx:1.24
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - /home/ubuntu/project/gan-shmuel/devops/nginx_pro.conf:/etc/nginx/nginx.conf:ro
    networks:
      - devops-network
    depends_on:
      - api

  


networks:
  devops-network:


