version: '3'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - ./.env
    restart: always
    networks:
      - network
      
  nginx:
    image: nginx:1.24
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - network

volumes:
  db:

networks:
  network:
