version: '3'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - ./.env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network
      
  nginx:
    image: nginx:1.24
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx-dev.conf:ro
    depends_on:
      - api
    networks:
      - network


networks:
  network:

