version: '3'
services:

# Devops
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - ./.env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx-network

  # Nginx
  nginx:
    image: nginx:1.24
    ports:
      - "8080:8080"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx-network


networks:
  nginx-network:

