version: '3'
services:

  # Weight
  weight:
    image: weight-image:0
    hostname: weight
    ports:
      - "8081:5000"
    env_file:
      - ./weight.env
    restart: always
    networks:
      - weight-network
    depends_on:
      mysql-weight:
        condition: service_healthy

  mysql-weight:
    image: mysql:8.3
    env_file:
      - ./weight.env
    restart: always
    networks:
      - weight-network
    volumes:
      - ./weight/db:/docker-entrypoint-initdb.d
      - weight_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s 
      retries: 20 


  # Billing
  billing:
    image: billing-image:0
    hostname: billing
    ports:
      - "8082:5000"
    env_file:
      - ./billing.env
    restart: always
    networks:
      - billing-network
    volumes:
      - ./billing/logs:/app/logs
      - ./in:/app/in
    depends_on:
      mysql-billing:
        condition: service_healthy

  mysql-billing:
    image: mysql:8.3
    env_file:
      - ./billing.env
    restart: always
    networks:
      - billing-network
    volumes:
      - ./billing/db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s 
      retries: 20 


volumes:
  weight_db_data:
  db-data:
  logs:

networks:
  billing-network:
  weight-network: