version: '3'
services:

  # Weight
  weight:
    image: weight-image:1
    hostname: weight
    env_file:
      - ./devops/weight.env
    restart: always
    ports:
      - "8081:5000"
    networks:
      - weight-network
    depends_on:
      mysql-weight:
        condition: service_healthy

  mysql-weight:
    image: mysql:8.3
    env_file:
      - ./devops/weight.env
    restart: always
    networks:
      - weight-network
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - weight_database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s 
      retries: 20 


  # Billing
  billing:
    image: billing-image:1
    hostname: billing
    env_file:
      - ./devops/billing.env
    restart: always
    ports:
      - "8082:5000"
    networks:
      - billing-network
    depends_on:
      mysql-billing:
        condition: service_healthy

  mysql-billing:
    image: mysql:8.3
    env_file:
      - ./devops/billing.env
    restart: always
    networks:
      - billing-network
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - billing_database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s 
      retries: 20 

  # # Nginx
  # nginx:
  #   image: nginx:1.24
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #     - "8082:8082"
  #   volumes:
  #     - /home/ubuntu/project/gan-shmuel/devops/nginx_pro.conf:/etc/nginx/nginx.conf:ro
  #   networks:
  #     - nginx-pro-network
  #     - devops-network
  #   depends_on:
  #     - api
  #     - billing
  #     - weight

# # Devops
#   api:
#     image: devops-image:1
#     env_file:
#       - ./devops/.env
#     restart: always
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     networks:
#       - devops-network

volumes:
  weight_database:
  billing_database:

networks:
  billing-network:
  weight-network:
