version: '3'
services:

  # Weight
  weight:
    image: weight-image:4
    env_file:
      - /home/ubuntu/gan/app/weight.env
    restart: always
    networks:
      - test-network
    depends_on:
      mysql-weight:
        condition: service_healthy

  mysql-weight:
    image: mysql:8.3
    env_file:
      - /home/ubuntu/gan/app/weight.env
    restart: always
    networks:
      - test-network
    volumes:
      - /home/ubuntu/gan/app/weight/db:/docker-entrypoint-initdb.d
      - testing_weight_database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s 
      retries: 20 


  # Billing
  billing:
    image: billing-image:4
    env_file:
      - /home/ubuntu/gan/app/billing.env
    restart: always
    networks:
      - test-network
    volumes:
      - /home/ubuntu/gan/app/billing/logs:/app/logs
      - /home/ubuntu/gan/app/billing/in:/app/in
    depends_on:
      mysql-billing:
        condition: service_healthy

  mysql-billing:
    image: mysql:8.3
    env_file:
      - /home/ubuntu/gan/app/billing.env
    restart: always
    networks:
      - test-network
    volumes:
      - /home/ubuntu/gan/app/billing/db-init:/docker-entrypoint-initdb.d
      - tesing_billing_database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s 
      retries: 20 
      

volumes:
  tesing_weight_database:
  tesing_billing_database:

networks:
  test-network: