version: '3'
services:

  # Weight
  weight:
    image: weight-image:3
    env_file:
      - ./weight.env
    restart: always
    networks:
      - test-network
    depends_on:
      mysql-weight:
        condition: service_healthy

  mysql-weight:
    image: mysql:8.3
    env_file:
      - ./weight.env
    restart: always
    networks:
      - test-network
    volumes:
      - ./weight/db:/docker-entrypoint-initdb.d
      - weight_database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s 
      retries: 20 


  # Billing
  billing:
    image: billing-image:3
    env_file:
      - ./billing.env
    restart: always
    networks:
      - test-network
    depends_on:
      mysql-billing:
        condition: service_healthy

  mysql-billing:
    image: mysql:8.3
    env_file:
      - ./billing.env
    restart: always
    networks:
      - test-network
    volumes:
      - ./billing/db-init:/docker-entrypoint-initdb.d
      - billing_database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s 
      retries: 20 
      

volumes:
  weight_database:
  billing_database:

networks:
  test-network: