version: '3'
services:

# Devops
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:5000"
    env_file:
      - ./.env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh/:/root/.ssh/
    networks:
      - devops-network

networks:
  devops-network:


