services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs

  db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: 'billing'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
  logs: