services:
  db:
    image: mysql:8.3
    hostname: ${MYSQL_HOST}
    volumes:
      - weight_db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=weight
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   timeout: 5s 
    #   retries: 20 

  api:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
      # db:
      #  condition: service_healthy
    volumes:
      - ./in:/in

volumes:
  weight_db_data:


